### ISSUE TITLE
What is the difference between hitmin and hitdiff?

### ISSUE THREAD

**Issue by donovan-parks** [muellan/metacache#44]
Hi,

Can you provide some clarity on what the difference is between hitmin and hitdiff? These have the same description in the CLI. Also, can you clarify what it means to have the default value of these parameters set to zero. Presumably a read needs at least 1 feature (k-mer) to match for it to be classifier so I'm not clear how to interpret the default being zero.

Thanks,
Donovan

**Comment by mpwweihrauc** [comment]
I came across this: https://muellan.github.io/metacache/afs.html

"Important: For abundance analysis tasks involving large eukaryotic genomes, make sure to supply options

-max-cand 4 -hitmin 4 -hitdiff 80

for optimal results. This tells MetaCache to consider the 4 best matching candidates per read (the default is 2, which is fine for bacteria). It also makes sure that the best matching candidate wins over the lowest common ancestor of all candidates if the input read has at least 80% features more in common with this best candidate than it has with the 2nd best."

I hope this is helpful.

Best,
Martin

**Comment by Funatiq** [comment]
I am sorry that the documentation for hitdiff is not great. You can see how it works in the code [here](https://github.com/muellan/metacache/blob/master/src%2Fclassification.cpp#L159). Basically for large numbers of hits, it  decreases the threshold more to consider more targets. hitmin is the basic range of hits that are considered below the target with the most hits. It is also the minimum number of hits that a target must have, so that a read can be classified.

**Comment by muellan** [comment]
To clearify the basic terminology further:

`hit-min` = how many features (kmer-hashes) must a sequence region accumulate in order to be considered to be a mapping candidate
 
`max-cand` = how many different sequences/targets are considered that have at least `hit-min` many hits

**Comment by donovan-parks** [comment]
Thanks André. This is a big help and makes a lot of sense.
