### ISSUE TITLE
metacache-build-refseq and download-ncbi-genomes not downloading genomes

### ISSUE THREAD

**Issue by sturne29** [muellan/metacache#6]
Just tried to build the database for Metacache, but neither of these commands are actually downloading the genomes. I tried the metacache-build-refseq first, then when it didn't download any, I tried the download-ncbi-genomes, thinking I might need to download them 'manually', as it were. Neither command gives an error per se; both download the assembly_summary.txt file, then when that's finished, give the following line and return to prompt:

> cat: ftpdirpaths: input file is output file

Any ideas what I'm doing wrong? I was really intrigued by the paper and wanted to see how the tool performed on my data.

**Comment by muellan** [comment]
Maybe the NCBI changed something on their servers or I accidentaly broke the download script on one of the last commits. I'll check it out.

**Comment by muellan** [comment]
Fixed it. The scripts should work again.

**Comment by muellan** [comment]
By the way: Note that the NCBI RefSeq has grown quite a bit since the paper was published. This means the default database is now around 28GB on disk and around 37 GB in memory. This also impacts the query speed. 

If you want to process the mapping data with some other tool you should also have a look on the output formatting options (shortly explained in the README and in "docs/query.txt".
